services:
  - docker

git:
  lfs_skip_smudge: true

language: python

branches:
  only:
    - master
    # build release tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - docker pull veros/ubuntu:18.04

install:
  - docker build -t veros -f testing.dockerfile .

env:
  global:
    - PYTHON_EXEC=python3
    - PYOM2_LIB=/usr/local/lib/pyOM_code_py3.so
    - OMP_NUM_THREADS=2
    - OMPI_MCA_mpi_yield_when_idle=1
  matrix:
    - VEROS_BACKEND=numpy PYTHON_EXEC=$PYTHON_EXEC PYOM2_LIB=$PYOM2_LIB
    - VEROS_BACKEND=bohrium BH_STACK=openmp PYTHON_EXEC=$PYTHON_EXEC PYOM2_LIB=$PYOM2_LIB

script:
  - docker run -e BH_STACK -t veros $PYTHON_EXEC -m bohrium_api --info
  - "docker run \
      -e CODECOV_TOKEN \
      -e VEROS_BACKEND \
      -e BH_STACK \
      -e OMP_NUM_THREADS \
      -e OMPI_MCA_mpi_yield_when_idle \
      -t veros \
      /bin/bash -c \"\
          $PYTHON_EXEC -m pytest . -v --cov --pyom2-lib $PYOM2_LIB --backend $VEROS_BACKEND && codecov \
      \"\
    "
  - pip install -r doc/requirements.txt && make -C doc html  # build docs

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "YS6vZDKyuwpbv4f6wM5WOEScmkPGNjK3LmzA5lsoOi7MQSw0qLB1pwM2Ewy2u054gdDmsy2UFubh7qzaYksinYzUCRPJ8mbLqc0ZsrYgwF9YhfPlPNE7gmbkVu9G7XggKq6aS/hvlMqwhHE15LvdzpMbhNBaOK7LDeV75D5lY2LHgS3x9al0f6cB60Y8jIqBVBVGbOw9TPPjhKG60f/0p9oDx+ogvh2MnlecMxxq8iEUb0os7OY0hqzbtzyhlMoZqOe2Tcu8xlUXXBPA/di83xHyHMlwFxWQN2jDvblx1/r4dBHrzBRS4Fx/pQW4NC+r0AQpvtnVpujbmF4sIwuzZxQkPEfPRjcREn3dysB3ntaLd+/6nGgC3znfiuaLV3NDZRABexESy6bp9lLJPmrdeeNVf+V5zTu7ArUiE5mlbjdudT6nHJ1Y5L26q3Irz+jnyjMU/mxqqIvYeruRi4sLyQ4pDnCXWBgGTu4P8Z55eC2xzAxb8ev4zX3Awe9Loy0TnYEbKk9bBlZQTmC6bGu2zDRG1/6Aqa9esysWCeZ3QcgFNh05iPeuyBW6WfdNoWWB0eAy+Gnxx3mHhP8G6OfEFK1uvTzmKtTqzH4C6Hy9n78xosOQ1BpLu0Fy6D+7S4CZChQEqD/dgxDyIJqTNvIGU8u2gjSYHuHt6dI17lf/Dv8="
  on:
    tags: true
  skip_existing: true

notifications:
  email: false
