name: Run tests

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-20.04]
        python-version: [3.6, 3.9]
        backend: [numpy, jax]

    env:
      VEROS_BACKEND: ${{ matrix.backend }}

    steps:
      - uses: actions/checkout@v2

      # make sure tags are fetched so we can get a version
      - run: |
          git fetch --prune --unshallow --tags

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system requirements
        run: sudo apt-get install libopenmpi-dev petsc-dev hypre-dev

      - name: Build PyOM2
        run: |
          pip install numpy  # get f2py
          mkdir -p /pyom2
          cp vendor/pyom2/pyOM2.1.0.tar.gz /pyom2
          cp vendor/pyom2/pyOM2_site_specific /pyom2/site_specific.mk_
          cd /pyom2
          tar xzf pyOM2.1.0.tar.gz
          make -C py_src -j 4 > /dev/null

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel cython
          pip install petsc4py==3.12
          pip install .[test]

      - name: Run tests sequentially
        run: pytest .

      - name: Run tests with MPI
        run: mpirun -host localhost:2 -v -np 2 pytest .
