name: Run tests

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-20.04]
        python-version: [3.6, 3.9]
        backend: [numpy, jax]

    env:
      VEROS_BACKEND: ${{ matrix.backend }}
      PYOM2_DIR: $HOME/pyom2

    steps:
      - uses: actions/checkout@v2

      # make sure tags are fetched so we can get a version
      - run: |
          git fetch --prune --unshallow --tags

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system requirements
        run: |
          sudo apt-get update
          sudo apt-get install libopenmpi-dev libpetsc-real3.12-dev
          echo "PETSC_DIR=/usr/lib/petscdir/petsc3.12/x86_64-linux-gnu-real" >> $GITHUB_ENV

      - name: Build PyOM2
        run: |
          pip install numpy  # get f2py
          mkdir -p $PYOM2_DIR
          cp vendor/pyom2/pyOM2.1.0.tar.gz $PYOM2_DIR
          cp vendor/pyom2/pyOM2_site_specific $PYOM2_DIR/site_specific.mk_
          cd $PYOM2_DIR
          tar xzf pyOM2.1.0.tar.gz
          make -C py_src -j 4 > /dev/null
          echo "PYOM2_LIB=$(readlink -f py_src/pyOM_code.*.so)" >> $GITHUB_ENV
          echo "PYOM2_LIB_MPI=$(readlink -f py_src/pyOM_code_MPI.*.so)" >> $GITHUB_ENV

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel cython mpi4py
          pip install -I petsc4py==3.12
          pip install .[test]

      - name: Run tests sequentially
        run: pytest . -v --cov --pyom2-lib $PYOM2_LIB

      - name: Run tests with MPI
        run: mpirun -host localhost:2 -v -np 2 pytest . -v --cov --pyom2-lib $PYOM2_LIB_MPI
